#if (UNITY_EDITOR && !IGNORE_UNITY_EDITOR) || DEVELOPMENT_BUILD
#define DEVELOPMENT
#endif // (UNITY_EDITOR && !IGNORE_UNITY_EDITOR) || DEVELOPMENT_BUILD

namespace FieldDay.HID.XR {
    public class XRStateMgr {
#if USING_XR && !UNITY_WEBGL

#endif // USING_XR && !UNITY_WEBGL
    }
}